//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProg.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankQuesions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankQuesions()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int id { get; set; }
        public int idQuesion { get; set; }
        public int idAnswer { get; set; }
        public bool Variants { get; set; }
        public int idCategory { get; set; }
        public int idTheme { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Category Category { get; set; }
        public virtual Question Question { get; set; }
        public virtual Theme Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
    }
}
