
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TestProg.Bd
{

using System;
    using System.Collections.Generic;
    
public partial class BankQuesions
{

    public int id { get; set; }

    public int idQuesion { get; set; }

    public string VariantsOne { get; set; }

    public string VariantsTwo { get; set; }

    public string VariantsThree { get; set; }

    public string VariantsFour { get; set; }

    public int idCategory { get; set; }

    public int idTheme { get; set; }



    public virtual Category Category { get; set; }

    public virtual Question Question { get; set; }

    public virtual Theme Theme { get; set; }

}

}
