

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TestProg.Bd
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class proektBDEntities : DbContext
{
    public proektBDEntities()
        : base("name=proektBDEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Answer> Answer { get; set; }

    public virtual DbSet<BankQuesions> BankQuesions { get; set; }

    public virtual DbSet<Category> Category { get; set; }

    public virtual DbSet<Question> Question { get; set; }

    public virtual DbSet<Result> Result { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Theme> Theme { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

