
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TestProg.Bd
{

using System;
    using System.Collections.Generic;
    
public partial class Theme
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Theme()
    {

        this.BankQuesions = new HashSet<BankQuesions>();

    }


    public int id { get; set; }

    public string ThemeName { get; set; }

    public Nullable<double> Status { get; set; }

    public int IdCategory { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BankQuesions> BankQuesions { get; set; }

    public virtual Category Category { get; set; }

}

}
